### PR TITLE
Cleanup filetree and fix syntax error in netatalk executable makefile

### PR DESCRIPTION
**Pull request by dgsga**
This commit removes two redundant files in etc/afpd and fixes a syntax error in the Netatalk makefile. Both libs and cflags for libevent now appear in the configuration summary.

### CODE REVIEW

**Comment by dgsga** [comment]
> @dgsga Thanks for the PR! I did notice that the libevent check behaved weirdly when bootstrapping on FreeBSD and OpenIndiana in particular, so good job cleaning up that part of the makefile.
> 
> Would you mind creating an issue ticket for this so that we can add it to the next 3.1 release candidate? 
Issue ticket created #342
>The makefile fix should definitely make it into the next patch release, IMO. Last time it got a bit messy when preparing the 3.1.15 release candidate so I'd like to do a bit more structured approach moving forward:
> 
> 1. Cut ticket and assign target-netatalk-3-1 label
> 2. Describe problem and solution in ticket
> 3. Raise PR
> 4. Review & merge
> 5. At the time of release tagging, pull the list of release candidate PRs using the label, and then cherry-pick into branch-netatalk-3-1
> 
> What do you think?
I know very little about GitHub release protocol but very happy to go with a more structured approach. While we are on our way to 3.1.16 shouldn't the development version be 3.1.16dev?

**Comment by rdmark** [comment]
Thanks for the ticket!

And sure, let's bump the 3.1 branch version to 3.1.16dev. I think keeping the main branch dev version to a blanket 3.1.99dev still makes sense though. But I'm open to counter arguments!

**Comment by dgsga** [comment]
TBH I don't 'get' having main and 3.1 branches, it seems like unnecessary duplication to me. Could we not create releases from main as it *is* the 3.1 branch. I may be missing something obvious though :)

**Comment by rdmark** [comment]
It's a good question! Are you subscribed to the mailing lists by any chance? There was some discussion on this topic a few months back. The one legitimate reason to keep branch-netatalk-3-1 right now, I think, is because of https://github.com/Netatalk/netatalk/issues/220 . If major breaking / intrusive changes start happening on `main`, in preparation for a new feature release (3.2? 4.0?), it makes sense to have a stable branch for patch releases. That said, no coding has happened yet for bringing appletalk back in `main` so it's kind of a moot point.... (my fault; life has gotten in the way of that project)

**Pull request merged**
