### PR TITLE
Modernize autotools bootstrapping

### PR DESCRIPTION
**Pull request by dgsga**
This PR:

1. Updates the autoconf syntax in bootstrap and configure.ac and updates all obsolete macros.
2. Fixes the make check error that occurs when AM_INIT_AUTOMAKE([subdir-objects]) is present in configure.ac.

### CODE REVIEW

**Comment by rdmark** [comment]
Great job figuring this out! My eyes go watery every time I try to wrap my head around bootstrap syntax. ;)

Did you test if / how much this breaks backwards compatibility with older autotools? It might be helpful to mention this in future release notes.

**Comment by rdmark** [comment]
Additionally, these changes introduce the following warnings on Debian Bullseye:
```
doc/manpages/man1/Makefile.am:35: warning: '%'-style pattern rules are a GNU make extension
doc/manpages/man5/Makefile.am:21: warning: '%'-style pattern rules are a GNU make extension
doc/manpages/man8/Makefile.am:21: warning: '%'-style pattern rules are a GNU make extension
```

I will test on a few more platforms.

**Comment by dgsga** [comment]
> Additionally, these changes reveal the following warnings on Debian Bullseye:
> 
> ```
> doc/manpages/man1/Makefile.am:35: warning: '%'-style pattern rules are a GNU make extension
> doc/manpages/man5/Makefile.am:21: warning: '%'-style pattern rules are a GNU make extension
> doc/manpages/man8/Makefile.am:21: warning: '%'-style pattern rules are a GNU make extension
> ```
> 
> [This page](https://www.gnu.org/software/make/manual/html_node/Suffix-Rules.html) talks about pattern rules.
> 
> Of course this code change didn't introduce the offending syntax, but it would be a plus to address it for the sake of portability.

Fixed in latest force-push

**Comment by rdmark** [comment]
It is possible to bootstrap, configure and build on recent OpenIndiana, FreeBSD, CentOS, and Debian Bookworm / Bullseye. I think this syntax is good.

**Comment by rdmark** [comment]
@dgsga May I ask you to squish the commits and mention the GitHub ticket # (https://github.com/Netatalk/netatalk/issues/331) in the commit description? It's helpful to have that traceability.

See also: https://github.com/Netatalk/netatalk/wiki/Developer-Notes#commit-messages

**Comment by rdmark** [comment]
BTW I learned about `autoupdate` today, which modernizes the autotools syntax, and it found only one minor recommended tweak:

```
dmark@rasp32:~/dev/netatalk $ autoupdate
dmark@rasp32:~/dev/netatalk $ git diff
diff --git a/configure.ac b/configure.ac
index 324ca503..6be04d09 100644
--- a/configure.ac
+++ b/configure.ac
@@ -1,6 +1,6 @@
 dnl configure.ac for netatalk

-AC_INIT([netatalk],m4_normalize(m4_include([VERSION])))
+AC_INIT([netatalk],[m4_normalize(m4_include(VERSION))])
 AC_CONFIG_SRCDIR([etc/afpd/main.c])

 NETATALK_VERSION=`cat $srcdir/VERSION`
```

**Comment by dgsga** [comment]
> @dgsga May I ask you to squash the commits and mention the GitHub ticket # (#331) in the commit description? It's helpful to have that traceability.
> 
> See also: https://github.com/Netatalk/netatalk/wiki/Developer-Notes#commit-messages

Done

**Comment by rdmark** [comment]
@dgsga The macOS job is failing with `ld: library not found for -lzlib` now...

**Comment by dgsga** [comment]
> @dgsga The macOS job is failing with `ld: library not found for -lzlib` now...

Yes, something unpleasant has happened in a recent update to Ventura :(
The current upstream master fails to build with the same error. Currently I have no idea why.

**Comment by rdmark** [comment]
Still failing on Monterey? What's going on!

**Comment by dgsga** [comment]
Hi @rdmark. It turns out the issue is with a bug in upstream mysql version 8.0.33. A bug fix request has been submitted to the maintainers. In the meantime the macOS workflow installs mysql version 8.0.32, a temporary workaround until the mysql issue is fixed.

**Pull request merged**
