### PR TITLE
It should be possible to disable setting of RPATH #45

### PR DESCRIPTION
**Pull request by andy-js**

### CODE REVIEW

**Comment by andy-js** [comment]
I also took the opportunity to straighten out the host_os definition for GNU/kFreeBSD.

**Comment by andy-js** [comment]
I'm waiting for this to be accepted or rejected before I prepare my next pull request.

**Comment by slowfranklin** [comment]
Can you please add a line to NEWS that documents the change? Thanks!

**Comment by slowfranklin** [comment]
Beware, just pushed some changes that will conflict with NEWS updates if you don't pull them beforehand. :)

**Comment by andy-js** [comment]
Done.

**Comment by slowfranklin** [comment]
Pushed, Ttanks!

**Pull request closed without merging**
