### PR TITLE
Bump to version 1.0.0 of bstrlib

### PR DESCRIPTION
**Pull request by rdmark**
https://github.com/websnarf/bstrlib/releases/tag/v1.0.0

### CODE REVIEW

**Review by dgsga — APPROVED** [review]
Quality.

I see the bounds check in bstrlib.c
```
	/* Did the operation complete successfully within bounds? */
	if (n >= (l = b->slen + (int) (strlen) ((char *) b->data + b->slen))) {
```
satisfies the Sonarcloud security warning  'make sure use of "strlen" is safe here'.

**Comment by rdmark** [comment]
@dgsga This is my read, too!

As a side note, the same line existed before this changeset, except a const qualifier was dropped.

**Comment by rdmark** [comment]
Reverting to draft. I want to spend a little more time analyzing the Sonar reported issues to make sure we don't introduce new bugs.

**Comment by rdmark** [comment]
I confirmed that none of the Sonar reported bugs are new, or significant. There is some layout changes and moving code around that triggers scanning.

**Pull request merged**
