### PR TITLE
Remove hard dependency on perl and grep

### PR DESCRIPTION
**Pull request by rdmark**
When perl and grep are not detected, don't generate or install the apple_dump/asip-status/macusers scripts and man pages.

### CODE REVIEW

**Review by dgsga — APPROVED** [review]
@rdmark, I have reformatted some of the meson.build files for the sake of consistency throughout the repository. I use muon fmt to format all the meson.build files as it applies the meson syntax recommendations to all files.
https://github.com/annacrombie/muon

Install muon and save the following script as 'muonfmt' in your local bin directory (chmod +x it too):
```
#!/bin/bash

find . -type f -name "meson.build" -exec muon fmt -i {} \;
```
Then all you need to do is:
```
cd netatalk
muonfmt
```

**Comment by rdmark** [comment]
Pushed a few final bugfixes and updated the manual to indicate that Perl is now an optional dependency.

**Comment by rdmark** [comment]
@dgsga What do you think about documenting the muonfmt trick on the Developer Notes wiki page? https://github.com/Netatalk/netatalk/wiki/Developer-Notes

**Comment by rdmark** [comment]
Created a new section on that page https://github.com/Netatalk/netatalk/wiki/Developer-Notes#build-system

**Pull request merged**
