### PR TITLE
Remove bundled libevent

### PR DESCRIPTION
**Pull request by rubenk**
It is ancient and doesn't compile on Fedora Rawhide.
Most modern distributions ship with libevent now.

### CODE REVIEW

**Comment by mfwitten** [comment]
I agree wholeheartedly; this dependency is better handled by the end-user.

-------------

I've taken the liberty of "backporting" this removal to `branch-netatalk-3-0`, and then merging the resulting commit with `branch-netatalk-3-1`, and then merging the resulting commit with `master'; these commits can be retrieved as follows:

    git fetch https://github.com/mfwitten/Netatalk.git \
      'refs/heads/tmp/libevent-removed/*:refs/heads/tmp/libevent-removed/*'

Then, you can see that there is a clearly recorded cross-branch alteration:

    $ log --graph --oneline -3 tmp/libevent-removed/master
    *   b87fedac (HEAD -> tmp/libevent-removed/master) Merge removal of bundled libevent
    |\
    | *   fd9034b9 (tmp/libevent-removed/branch-netatalk-3-1) Merge removal of bundled libevent
    | |\
    | | * be42f030 (tmp/libevent-removed/branch-netatalk-3-0) Remove bundled libevent

Your authorship has been preserved:

    $ git log -1 tmp/libevent-removed/branch-netatalk-3-0
    commit be42f030ee3fa4d070166aabeaf26bb4039aee8c
    Author: Ruben Kerkhof <ruben@rubenkerkhof.com>
    Date:   Fri Apr 27 00:31:46 2018 +0200
    
        Remove bundled libevent
        
        It is ancient and doesn't compile against modern
        dependencies; also, modern distributions tend to
        ship with libevent now.
        
        Co-authored-by: Michael Witten <mfwitten@gmail.com>

The easiest way to apply all this would be for @slowfranklin or @hat001 to fetch the commits as described above, and then push each one into its respective branch:

    git push https://hat001@github.com/Netatalk/Netatalk.git \
      'refs/heads/tmp/libevent-removed/*:refs/heads/*'

If done now, before any other pushes, that should yield fast-forward "merges" for each one, and then this pull request may be closed.

**Comment by slowfranklin** [comment]
sorry, but nak. We need this for OSes that don't ship libevent. Can you make it
a configure option instead?

-- 
-slow

-- 
Ralph Boehme, Samba Team       https://samba.org/
Samba Developer, SerNet GmbH   https://sernet.de/en/samba/
GPG Key Fingerprint:           FAE2 C608 8A24 2520 51C5
                               59E4 AA1E 9B71 2639 9E46

**Comment by rubenk** [comment]
I can look into that, but which distro doesn't ship libevent these days?

**Comment by slowfranklin** [comment]
On Tue, May 15, 2018 at 05:52:11AM -0700, Ruben Kerkhof wrote:
> I can look into that, but which distro doesn't ship libevent these days?

then one "distro" I care about here is Solaris 11. :)

-slow

-- 
Ralph Boehme, Samba Team       https://samba.org/
Samba Developer, SerNet GmbH   https://sernet.de/en/samba/
GPG Key Fingerprint:           FAE2 C608 8A24 2520 51C5
                               59E4 AA1E 9B71 2639 9E46

**Comment by rubenk** [comment]
And using the one from OpenCSW isn't an option?

**Comment by slowfranklin** [comment]
On Tue, May 15, 2018 at 05:54:49AM -0700, Ruben Kerkhof wrote:
> And using the one from OpenCSW isn't an option?

unfortunately not. I need to be able to ship a self contained binary package
where the only external deps are base OS libraries.

-slow

-- 
Ralph Boehme, Samba Team       https://samba.org/
Samba Developer, SerNet GmbH   https://sernet.de/en/samba/
GPG Key Fingerprint:           FAE2 C608 8A24 2520 51C5
                               59E4 AA1E 9B71 2639 9E46

**Comment by andy-js** [comment]
I don't think having libevent as an external dependency is really that big of a deal.  And if we want to ship binaries packages that include it we can still do that.

**Comment by slowfranklin** [comment]
On Tue, May 15, 2018 at 06:14:08AM -0700, Andrew Stormont wrote:
> I don't think having libevent as an external dependency is really that big of a deal.

it is for me. :) I wholeheartedly agree that we should not be using it by
default and offer a configure option and check, much like we do it for eg tdb
iirc. But simply removing it is not an option, sorry.

-slow

-- 
Ralph Boehme, Samba Team       https://samba.org/
Samba Developer, SerNet GmbH   https://sernet.de/en/samba/
GPG Key Fingerprint:           FAE2 C608 8A24 2520 51C5
                               59E4 AA1E 9B71 2639 9E46

**Comment by andy-js** [comment]
If you are already building netatalk from source building libevent first doesn't seem like it's much of a stretch.  What am I missing?

**Comment by mfwitten** [comment]
@slowfranklin 
Because you're building the binaries, you should have complete control over the build environment.

* You could provide any version of `libevent` you want as a static dependency, or even bundle it has a dynamic dependency.
* If you're building a binary for some system that *does* ship `libevent`, then I suggest obtaining a copy of the relevant files so that you can build against the system's actual software base.
* It might be worthwhile to look into one of these "deterministic" build environment solutions, so that these issues don't seem so adhoc.

**Comment by rubenk** [comment]
In the long run keeping the bundled libevent up to date (which it now isn't) seems like much more work than a day, including handling all the reports of issues that have been fixed in upstream libevent.

There's also a security risk, and the fact that the libs are installed in /usr/lib, potentially conflicting with libevent from distros.

**Comment by slowfranklin** [comment]
On Tue, May 15, 2018 at 08:23:30AM -0700, Michael Witten wrote:
> @slowfranklin @rubenk 
> Here's a compromise solution: How about there be created a new, separate
> repository whose sole purpose is to provide anyone with the tools necessary to
> automate binary builds of the main source repository?
> 
> Someone who has time (e.g., perhaps me or @rubenk or @andy-js) can get this
> binary-build infrastructure working, and *then* it will be a simple matter of
> removing `libevent` from the main repository and using the new binary-build
> infrastructure to deal with building.

sounds much too complicated. All that's really needed is a configure check to
prefer and consume an installed libevent over the bundled one.

If none of the folks who are driving this change here is willing or able to do
this, I can code something up after SambaXP, but I'm currently much too busy
with other stuff. Feel free to ping me after SambaXP in regular intervals. :)

-slow

-- 
Ralph Boehme, Samba Team       https://samba.org/
Samba Developer, SerNet GmbH   https://sernet.de/en/samba/
GPG Key Fingerprint:           FAE2 C608 8A24 2520 51C5
                               59E4 AA1E 9B71 2639 9E46

**Comment by rubenk** [comment]
I just checked, there already is a configure flag:
```
netatalk (master %=) > ./configure --help | grep -i event
  --with-libevent         whether to use the bundled libevent (default: yes)
  --with-libevent-header  path to libevent header files
  --with-libevent-lib     path to libevent library
```

**Comment by slowfranklin** [comment]
On Tue, May 15, 2018 at 10:14:53AM -0700, Ruben Kerkhof wrote:
> I just checked, there already is a configure flag:
> ```
> netatalk (master %=) > ./configure --help | grep -i event
>   --with-libevent         whether to use the bundled libevent (default: yes)
>   --with-libevent-header  path to libevent header files
>   --with-libevent-lib     path to libevent library
> ```

oh, looks like I already did this just 6 years ago. I somehow forgot... :)

-slow

-- 
Ralph Boehme, Samba Team       https://samba.org/
Samba Developer, SerNet GmbH   https://sernet.de/en/samba/
GPG Key Fingerprint:           FAE2 C608 8A24 2520 51C5
                               59E4 AA1E 9B71 2639 9E46

**Comment by slowfranklin** [comment]
The day has come! Let's finally remove libevent, cf MR #132. Closing this one. Thanks for contributing!

**Pull request closed without merging**
