### PR TITLE
libatalk: Remove special case for COMMENT metadata validation

### PR DESCRIPTION
**Pull request by rdmark**
Remove special handling of COMMENT ad entries, since empty entries are now allowed as of the code changes in https://github.com/Netatalk/netatalk/pull/178

### CODE REVIEW

**Comment by southbay82** [comment]
Can't wait to see this in a release!

**Comment by rdmark** [comment]
@southbay82 For the record, the more important fix which addresses the fatal internal errors is in https://github.com/Netatalk/netatalk/pull/178 which I merged to main yesterday.

The current PR has been repurposed for some minor cleanup of the logic to consolidate the two rounds of fixes for the same CVE regression.

**Comment by rdmark** [comment]
@slowfranklin I'm proposing we restore the cleanup of xattr metadata that fail the validity check now. The safeguard in https://github.com/Netatalk/netatalk/commit/f90031aecde6372a26055541f63072ebbc821de6 has been live now since 3.1.13 in January, and we've gotten about half a dozen user reports. They all point towards empty entries on certain directories as the culprit. So with the fix in https://github.com/Netatalk/netatalk/pull/178 allowing empty entries again, I think it should be safe to go back to cleaning up anything that fails the check.

What do you think?

**Comment by slowfranklin** [comment]
> What do you think?

To be honest, I don't know. I would have to spend much more time to drill into this than I can affort atm. Sorry!

**Comment by rdmark** [comment]
@slowfranklin Fair enough. To hedge the risk, I propose that we only merge the change to COMMENT entry handling, and keep the invalid entry assertion intact for one more release cycle. This will help us catch any potential remaining corner cases.

I've repurposed this PR for the smaller change, adding a TODO, and raised https://github.com/Netatalk/netatalk/issues/400 to track the next step.

**Pull request merged**
