### PR TITLE
Provide MNTTYPE_NFS on OmniOS / Solaris

### PR DESCRIPTION
**Pull request by rdmark**
Forward-port of https://github.com/Netatalk/Netatalk/pull/190

### CODE REVIEW

**Comment by rdmark** [comment]
Partially addresses https://github.com/Netatalk/Netatalk/issues/117

**Comment by rdmark** [comment]
Merged this without code review since it's a forward port of a reviewed PR.

**Comment by slowfranklin** [comment]
Hi Daniel,

I guess we can just skip creating MRs for copying patches from the 3-1 
branch to master.

Instead, we can simply rebase 3-1 on top of master and push the result 
to master, like so:

$ git checkout branch-netatalk-3-1
$ git checkout -b for-master
$ git rebase -i origin/master
... verify commits, removing 3-1 specific ones (~30 commits)...

The resulting branch "for-master" will have all missing commits from 3-1 
applied on-top of master.

As there's no real development happening, master doesn't see any 
activity so I wondered whether it might be easier to reset the master 
branch to the 3-1 head and then delete the 3-1 branch...

-slow

**Comment by rdmark** [comment]
Hi Ralph,

I'm supportive of removing the branch-netatalk-3-1 branch and using master
for 3.1 patches & releases.
This reduces maintenance overhead, which is unequivocally a good thing.

As a side note, while tinkering with the branches you may want to consider
renaming master to main.
Github has made this very frictionless: https://github.com/github/renaming

Best,
Daniel

**Comment by slowfranklin** [comment]
On 2/11/23 21:21, Daniel Markstedt wrote:
> I'm supportive of removing the branch-netatalk-3-1 branch and using master
> for 3.1 patches & releases.
> This reduces maintenance overhead, which is unequivocally a good thing.

ok.

I will implement the changes next weekend.

> As a side note, while tinkering with the branches you may want to consider
> renaming master to main.
> Github has made this very frictionless: https://github.com/github/renaming

good point. I'll do that as well.

-slow

-- 
Ralph Boehme, Samba Team                 https://samba.org/
SerNet Samba Team Lead      https://sernet.de/en/team-samba

**Pull request merged**
