### PR TITLE
Update URL for css stylesheet in manual pages

### PR DESCRIPTION
**Pull request by rdmark**
The css stylesheet for html manual pages is currently hard coded to an old sourceforge domain that isn't used anymore. As a result, the stylesheet isn't found and the manual pages stay unstyled. I think this is because the user agent refuses to load resources over insecure http in a https context.

### CODE REVIEW

**Review by dgsga — COMMENTED** [review]
I might be missing something obvious here but the doc/css/netatalk.css file does not appear to exist in the repo??

**Comment by rdmark** [comment]
That's a good question! The static web sources live in a different repo: https://github.com/Netatalk/netatalk-web/blob/main/css/netatalk.css

**Comment by rdmark** [comment]
But yes you're right, netatalk.css used to live in the main repo, under https://github.com/Netatalk/netatalk/tree/branch-netatalk-3-0/doc/gfx_and_css

I had it removed when I set up the netatalk-web repo and salvaged all the PHP code that had been living dangerously on the SF servers without revision control.

**Comment by dgsga** [comment]
> But yes you're right, netatalk.css used to live in the main repo, under https://github.com/Netatalk/netatalk/tree/branch-netatalk-3-0/doc/gfx_and_css
> 
> I had it removed when I set up the netatalk-web repo and salvaged all the PHP code that had been living dangerously on the SF servers without revision control.

Strange, I find on Debian 12 and macOS that the pages are already styled without this PR. Styling fails when this PR is applied. Hmmm...

**Comment by rdmark** [comment]
Right, this fix makes it so that the styles gets applied only when manual html pages are loaded from the remote server. e.g. https://netatalk.sourceforge.io/3.1/htmldocs/installation.html

The alternative solution is to just update the protocol and domain in the URL and keep it loading from remote... With the drawback that it might break in the future if sourceforge does another big change to their domain scheme.

**Comment by rdmark** [comment]
Force pushed a change to keep the absolute URL.

I think the reason it's not working remotely right now is that the user agent disallows loading resources over http for a site that's otherwise https

**Comment by rdmark** [comment]
FYI I went in a cleaned up all other http URLs in the website now. Also fixed a few errors to make it XHTML 1.0 Strict compliant

**Review by dgsga — APPROVED** [review]

**Pull request merged**
