### PR TITLE
Remove PGP UAM

### PR DESCRIPTION
**Pull request by NJRoadfan**
Addresses #1507

### CODE REVIEW

**Comment by rdmark** [comment]
@NJRoadfan Please resolve the merge conflict!

Also, it should be safe to remove the entire bundled wolfssl library now, right?

**Comment by rdmark** [comment]
Also note for self: The Dockerfile needs to be updated to remove the PGP option (and the nettle dependencies.)

**Comment by NJRoadfan** [comment]
Yes, it should be safe to remove. Also, there may be artifacts left in the `meson.build` file in the uams directory.

**Comment by rdmark** [comment]
Pro tip: Rather than a branch merge, if you do something like `git rebase main` you get a branch with clean commit history that you can force-push as is.

**Review by rdmark — CHANGES_REQUESTED** [review]
Looks good, but please squash the two commits into one by any means.

**Pull request closed without merging**
