### PR TITLE
[2.3] Create init scripts for macOS 

### PR DESCRIPTION
**Pull request by rdmark**
macOS style launchd template and helper script

### CODE REVIEW

**Comment by dgsga** [comment]
Path substitution barfs with the original unified plist (deja vu here), so have utilised the Netatalk script instead. Just need to test on VM tonight.

**Review by dgsga — APPROVED** [review]

**Comment by dgsga** [comment]
@rdmark, please can you review then merge the PR if you're happy with it. GitHub would only let me review it!

**Comment by rdmark** [comment]
@dgsga let me test this on my MacBook Pro tonight. If everything works I will merge

**Comment by rdmark** [comment]
Rebased and merged. Thanks for the assist!

**Pull request merged**
