### PR TITLE
Revert "libatalk: Restore invalid metadata cleanup in ad_open.c"

### PR DESCRIPTION
**Pull request by rdmark**
Reverts Netatalk/netatalk#513

### CODE REVIEW

**Comment by rdmark** [comment]
@dgsga All of a sudden we have multiple reports that the EA metadata validation still fails in some environments.

https://github.com/Netatalk/netatalk/issues/992
https://github.com/Netatalk/netatalk/discussions/993

I propose we revert this for now to buy us some time to get to the root of it, without blocking the 3.2.0 release. Thoughts?

**Comment by rdmark** [comment]
Some additional investigation needed first...

**Comment by dgsga** [comment]
@rdmark, I don't have any issue with this PR. IMHO the CVE regression fixes that were pushed to main have never been as simple and clean as @andychen-syno's original PR that was never accepted:

https://github.com/Netatalk/netatalk/commit/9e864d10dcc7cad9bf75185708793c3608d8ae6c

I use it on my fork and it produces a clean log with Mac OS 9 clients (unlike current main), none of these invalid metadata errors, and also allows for icon substitution for the AFP share as it should with this client OS.

**Review by dgsga — APPROVED** [review]

**Comment by rdmark** [comment]
@dgsga I'm open to suggestions!

In main we have both Andrew's and Andy's patches, the latter applied on top of the former.

The former was merged with https://github.com/Netatalk/netatalk/pull/174 and the latter with https://github.com/Netatalk/netatalk/pull/178

I'm all for revisiting the solution, since we're still facing this apparent fragility in that area...

**Comment by dgsga** [comment]
I'll prepare a draft PR...

**Comment by rdmark** [comment]
When working on the 3.2.0 release notes, I was reminded that we have a fix for macOS generated EA metadata with https://github.com/Netatalk/netatalk/pull/575 – closing this PR for now while evaluating if this is enough to resolve users' issues.

**Pull request closed without merging**
