### PR TITLE
Add Debian VM and improve readability of GitHub workflow

### PR DESCRIPTION
**Pull request by dgsga**

### CODE REVIEW

**Comment by dgsga** [comment]
Needed some surprising additions to both configure flags and apt-get install for compilation to succeed on the oldstable container...

**Comment by rdmark** [comment]
@dgsga Just a thought: how about “hard coding” the list of packages to install with apt for oldstable, and keep the global list of packages as-is? The former list is kind of a temporary workaround for the current Debian release cycle. I think it will look cleaner and be easier to maintain. What do you think?

**Comment by dgsga** [comment]
@rdmark, old stable packages are now hardcoded. I have also beautified the entire yaml document so it is now easy to see which packages are installed and which configure flags are used on each operating system.

**Review by rdmark — APPROVED** [review]
Gorgeous. :)

**Pull request merged**
