### PR TITLE
[2.4] meson: Fix linking of afpd with glibc on Debian Bullseye

### PR DESCRIPTION
**Pull request by rdmark**

### CODE REVIEW

**Comment by rdmark** [comment]
@dgsga FYI this only gets us halfway to building v2.x on bullseye with Meson. Linking of libatalk fails elsewhere.

**Comment by dgsga** [comment]
> @dgsga FYI this only gets us halfway to building v2.x on bullseye with Meson. Linking of libatalk fails elsewhere.

@rdmark, leave it with me.

**Comment by dgsga** [comment]
@rdmark, all fixed!

**Review by dgsga — APPROVED** [review]

**Comment by rdmark** [comment]
Cheers!

**Pull request merged**
