### PR TITLE
[2.2] Disable ACL and quota by default; remove a few antiquated checks

### PR DESCRIPTION
**Pull request by rdmark**

### CODE REVIEW

**Comment by slowfranklin** [comment]
Why disable ACL support by default?

**Comment by rdmark** [comment]
I thought it is an adjacent feature with little practical use today (especially for 2.2 users which are entirely hobby related). It's not causing build failures though so I'm not in a hurry to make the change. I can update the PR and remove the ACL changes.

**Comment by slowfranklin** [comment]
> I thought it is an adjacent feature with little practical use today (especially for 2.2 users which are entirely hobby related). It's not causing build failures though so I'm not in a hurry to make the change. I can update the PR and remove the ACL changes.

 I'm ok with disabling it by default in 2.2. Whatever you prefer. :)

**Comment by rdmark** [comment]
For the purpose of keeping the scope narrow and solving the actual problem, let's focus on quota in this PR. Updated!

**Review by slowfranklin — APPROVED** [review]

**Pull request merged**
