### PR TITLE
Name of function does not match name referenced in log message

### PR DESCRIPTION
**Pull request by szaydel**
It looks like this is just a typo.

### CODE REVIEW

**Comment by hat001** [comment]
Thanks.

**Comment by szaydel** [comment]
Were you planning on merging in the commit, or should I drop the branch? Thank you, Sam.

**Comment by hat001** [comment]
It's committed already.

master:
https://github.com/Netatalk/Netatalk/commit/5b1e5e11fda711a8a7471dc1e195ac267a0da61c

branch-netatalk-3-1:
https://github.com/Netatalk/Netatalk/commit/7b578331538108980bb05de2f89ab4fafae7237b

**Comment by slowfranklin** [comment]
On Thu, Jan 05, 2017 at 05:35:44AM -0800, HAT wrote:
> It's committed already.
> 
> master:
> https://github.com/Netatalk/Netatalk/commit/5b1e5e11fda711a8a7471dc1e195ac267a0da61c
> 
> branch-netatalk-3-1:
> https://github.com/Netatalk/Netatalk/commit/7b578331538108980bb05de2f89ab4fafae7237b

fwiw, while we can of course apply log message fixes to release branches, imho
it's sufficient to put such changes in master only.

But if you push changes to release branches, in the future please ensure a
corresponding bug is filed and referenced in the commit message. Thanks! :)

Cheerio!
-slow

**Comment by hat001** [comment]
I wrote GItHub's URL in the commit message.
Is this work insufficient?
Should I register it with SourceForge bug ?

**Comment by slowfranklin** [comment]
On Thu, Jan 05, 2017 at 06:06:40AM -0800, HAT wrote:
> I wrote GItHub's URL in the commit message.
> Is this work insufficient?
> Should I register it with SourceForge bug ?

ah, no, sorry, that's perfect. I missed that when only checking the commit
message in the github web view where the URL gets truncated to just

  <#78>

Sorry for the noise! :)

Cheerio!
-slow

**Comment by szaydel** [comment]
Thanks guys. :)

**Pull request closed without merging**
