### PR TITLE
[2.4] meson: set setuid bit to allow user afppasswd changing

### PR DESCRIPTION
**Pull request by rdmark**

### CODE REVIEW

**Review by dgsga — APPROVED** [review]
Fixed mini typo!

**Comment by rdmark** [comment]
...and the same notation is represented in the shell (Debian below), if you need corroborating evidence! The stark text highlighting is actually the reason I noticed this in the first place...

Screenshot 2024-06-05 at 23 59 30

**Comment by rdmark** [comment]
All that to say: Please let me know if you object to the reverting of your commit before merging this. I may have overlooked something. :)

**Comment by dgsga** [comment]
You learn something everyday! Quite happy for you to revert my fix 👍

**Pull request merged**
