### PR TITLE
Revert to iniparser v3 code in preparation for release

### PR DESCRIPTION
**Pull request by rdmark**
Temporarily revert to the previous version of iniparser

### CODE REVIEW

**Comment by rdmark** [comment]
@slowfranklin @dgsga I propose we temporarily roll back these changes in order to manage the cross-platform regression risk for a 3.1 patch release.

**Comment by rdmark** [comment]
@dgsga Sonarcloud scanning agrees with you -- security hotspots increase from 6 to 10. I see your argument about closing security holes and rolling forward. May I ask you to help me double check that no other local modification to the iniparser code fell off with this change? I.e. by looking at the commit history https://github.com/Netatalk/netatalk/commits/main/libatalk/iniparser

**Comment by dgsga** [comment]
> @dgsga Sonarcloud scanning agrees with you -- security hotspots increase from 6 to 10. I see your argument about closing security holes and rolling forward. May I ask you to help me double check that no other local modification to the iniparser code fell off with this change? I.e. by looking at the commit history https://github.com/Netatalk/netatalk/commits/main/libatalk/iniparser

Will do.

**Comment by rdmark** [comment]
Thanks for doing that!

I'm running some tests on Fedora / FreeBSD / OmniOS to check for regressions.

**Comment by rdmark** [comment]
Works ok on Fedora.
Failed to get it to compile on OmniOS because of libgcrypt, and FreeBSD because of libevent.

**Comment by rdmark** [comment]
I'm ok with the risk following the additional testing and analysis.

**Pull request closed without merging**
