### PR TITLE
Fix failures with double variable expansion when running configure #441

### PR DESCRIPTION
**Pull request by dgsga**
Please wake me up from this autotools nightmare...

### CODE REVIEW

**Comment by rdmark** [comment]
So the NONE problem is definitely gone!

However I think the default fallback substitution to `/usr/local` is malfunctioning when using configure overrides now.

For instance, this is a snippet from what the Debian package script does:

```
		--localstatedir=/var/lib \
		--sysconfdir=/etc \
		--with-pkgconfdir=/etc/netatalk \
```

However the generated paths in ./Makefile are all wrong:

```
localstatedir = /usr/local/var
sysconfdir = /usr/local/etc
pkgconfdir = /usr/local/etc
```

Similarly, the `--enable-fhs` overrides aren't taking effect either. As an experiment, I put the three substitutions *inside* the AC_ARG_ENABLE macro for --enable-fhs, and *then* the substitution did happen as expected. So the substitutions mustn't be happening at the right time in the macro right now...

**Comment by dgsga** [comment]
> So the NONE problem is definitely gone!
> 
> However I think the default fallback substitution to `/usr/local` is malfunctioning when using configure overrides now.
> 
> For instance, this is a snippet from what the Debian package script does:
> 
> ```
> 		--localstatedir=/var/lib \
> 		--sysconfdir=/etc \
> 		--with-pkgconfdir=/etc/netatalk \
> ```
> 
> However the generated paths in ./Makefile are all wrong:
> 
> ```
> localstatedir = /usr/local/var
> sysconfdir = /usr/local/etc
> pkgconfdir = /usr/local/etc
> ```
> 
> Similarly, the `--enable-fhs` overrides aren't taking effect either. As an experiment, I put the three substitutions _inside_ the AC_ARG_ENABLE macro for --enable-fhs, and _then_ the substitution did happen as expected. So the substitutions mustn't be happening at the right time in the macro right now...

I think this is getting far too complex. I'm going to try your suggestion throughout the codebase, namely:
>I'm starting to think that your very first proposal is the way to go... namely avoid substitution with double variable >expansion. Just use the first layer of ${prefix} substitution and hard-code the rest in the manual pages...

**Comment by rdmark** [comment]
Way too complex with potential for layers of cross-platform headaches...

**Comment by dgsga** [comment]
It's looking good so far. Which version of Debian and FreeBSD are you using so we have consistent test environments?

**Comment by rdmark** [comment]
Debian 12.0 Bookworm and FreeBSD 13.1

**Comment by dgsga** [comment]
Please can you pass on the ./configure args you are using for FreeBSD 13.1, make is failing on 13.2 with a dtrace error :(

**Comment by rdmark** [comment]
Weeeird. It compiles cleanly for me with zero args to ./configure

Maybe a missing dependency? I've left a few cursory notes at the wiki https://github.com/Netatalk/netatalk/wiki/Installation-Notes#freebsd-131

**Pull request closed without merging**
