### PR TITLE
Optimize FCE file modification event processing

### PR DESCRIPTION
**Pull request by seiman**
We noticed that the fce_api sends modified events later, even if  `fce holdfmod = 0` is specified.
If a file is deleted in the meantime the deletion event is send before the modified event.
### Tests
We have created the following tests to visualize the problem:
`echo "A" > test.txt ; echo "A" > test2.txt; echo "B" > test.txt; rm test.txt; rm test2.txt`
This leads to the following netatalk log:
` {fce_api.c:505} register_fce(path: /media/share/test.txt, event: FCE_FILE_CREATE)`
` {fce_api.c:505} register_fce(path: /media/share/test.txt, event: FCE_FILE_MODIFY)`
` {fce_api.c:458} save_close_event: /media/share/test.txt`
` {fce_api.c:505} register_fce(path: /media/share/test2.txt, event: FCE_FILE_CREATE)`
` {fce_api.c:505} register_fce(path: /media/share/test2.txt, event: FCE_FILE_MODIFY)`
` {fce_api.c:458} save_close_event: /media/share/test2.txt`
` {fce_api.c:505} register_fce(path: /media/share/test.txt, event: FCE_FILE_MODIFY)`
` {fce_api.c:458} save_close_event: /media/share/test.txt`
` {fce_api.c:505} register_fce(path: /media/share/test.txt, event: FCE_FILE_DELETE)`
` {fce_api.c:505} register_fce(path: /media/share/test2.txt, event: FCE_FILE_DELETE)`
` {fce_api.c:551} check_saved_close_events: sending event: /media/share/test.txt`
We are receiving these events:
`FceEvent(event=FCE_FILE_MODIFY, eventID=15, pid=43, path=/media/share/test.txt)`
`FceEvent(event=FCE_FILE_MODIFY, eventID=18, pid=43, path=/media/share/test.txt)`
`FceEvent(event=FCE_FILE_MODIFY, eventID=19, pid=43, path=/media/share/test2.txt)`
`FceEvent(event=FCE_FILE_DELETE, eventID=20, pid=43, path=/media/share/test.txt)`
`FceEvent(event=FCE_FILE_DELETE, eventID=21, pid=43, path=/media/share/test2.txt)`
`FceEvent(event=FCE_FILE_MODIFY, eventID=22, pid=43, path=/media/share/test.txt)`
-> The Modify event arrives after the delete.

`cp /somewhere/..../ONE_BIG_FILE .; rm ONE_BIG_FILE`
This leads to the following netatalk log:
` {fce_api.c:505} register_fce(path: /media/share/ONE_BIG_FILE, event: FCE_FILE_CREATE)`
` {fce_api.c:505} register_fce(path: /media/share/ONE_BIG_FILE, event: FCE_FILE_MODIFY)`
` {fce_api.c:458} save_close_event: /media/share/ONE_BIG_FILE`
` {fce_api.c:505} register_fce(path: /media/share/ONE_BIG_FILE, event: FCE_FILE_DELETE)`
` {fce_api.c:551} check_saved_close_events: sending event: /media/share/ONE_BIG_FILE`
We are receiving these events:
`FceEvent(event=FCE_FILE_DELETE, eventID=27, pid=43, path=/media/share/ONE_BIG_FILE)`
`FceEvent(event=FCE_FILE_MODIFY, eventID=28, pid=43, path=/media/share/ONE_BIG_FILE)`
-> The Modify event again arrives after the delete.

### Our Proposal
In case of `fce holdfmod = 0` we propose to send the modify events directly

### CODE REVIEW

**Comment by slowfranklin** [comment]
Can we somehow just check for pending modified events when a file is deleted and send out the pending events just before the deleted event then?

**Comment by seiman** [comment]
I don't really know why the  `fce holdfmod` has been written, but it seems that only the last modify event is being delayed.
We could add a feature, that other events(Move file, Delete file) check against this pending event,
**BUT:** a move of the directory above a file leads to a move event only for the directory.
To guarantee that the modify event is being send before the directory move we would require a path analysis and at that point i would recommend a major reengineering of the fce handling.

**Comment by slowfranklin** [comment]
Please rebase on current master and resubmit. Sorry for leaving it lingering for so long.

**Comment by rdmark** [comment]
This changeset has been rebased and filed with https://github.com/Netatalk/netatalk/pull/849

**Pull request closed without merging**
