### PR TITLE
[2.3] Rename launchd plist to io.netatalk* and sort file names

### PR DESCRIPTION
**Pull request by rdmark**

### CODE REVIEW

**Comment by rdmark** [comment]
This is an experiment for now so keeping as Draft.

**Review by dgsga — APPROVED** [review]

**Comment by dgsga** [comment]
It should work fine. I would also rename com.netatalk.daemon.plist.tmpl to io.netatalk.daemon.plist.tmpl and update the relevant makefiles too for the sake of consistency

**Comment by rdmark** [comment]
@dgsga Haven't I made those changes already in this PR though?

**Comment by dgsga** [comment]
> @dgsga Haven't I made those changes already in this PR though?

Yes you have!! My apologies for focussing on the lines removed rather than lines added.

**Pull request merged**
