### PR TITLE
Fix 'MAXPHYS' macro redefinition warning in macOS

### PR DESCRIPTION
**Pull request by dgsga**

### CODE REVIEW

**Comment by rdmark** [comment]
@dgsga any chance we can check for capabilities and not platform? What does this macro do in the first place anyways, and is it still needed?

**Comment by rdmark** [comment]
According to ChatGPT:

> In C, `MAXPHYS` is a macro that defines the maximum size of a single I/O transfer in bytes. It is often used in operating system kernel development to set limits on the size of data transfers. The value of `MAXPHYS` can vary depending on the operating system and hardware architecture. It's typically set to a value that optimizes performance and system stability.

**Comment by dgsga** [comment]
> According to ChatGPT:
> 
> > In C, `MAXPHYS` is a macro that defines the maximum size of a single I/O transfer in bytes. It is often used in operating system kernel development to set limits on the size of data transfers. **The value of `MAXPHYS` can vary depending on the operating system** and hardware architecture. It's typically set to a value that optimizes performance and system stability.

If this is the case it makes sense to check for platform...

**Comment by rdmark** [comment]
Fair point.

**Review by rdmark — APPROVED** [review]

**Pull request merged**
