### PR TITLE
[2.4] docker: Alpine based container + Meson build

### PR DESCRIPTION
**Pull request by rdmark**
Use Alpine Linux base image for Docker, and build with Meson for SPEED.

### CODE REVIEW

**Comment by rdmark** [comment]
This almost works now. But blocked by https://github.com/Netatalk/netatalk/issues/917

**Comment by rdmark** [comment]
It is even closer to working fully now. Unfortunately, there seems to be a segfault when running afppassw in the heredoc context.

```
dmark@alien:~/dev/netatalk2$ docker compose up
[+] Running 0/0
 ⠋ Container netatalk2-netatalk-1  Recreated                                                                       0.0s
Attaching to netatalk-1
netatalk-1  | *** Setting up users and groups
netatalk-1  | /entrypoint.sh: line 23:    12 Segmentation fault      (core dumped) afppasswd -a "${AFP_USER}" <<EOD
netatalk-1  | $AFP_PASS
netatalk-1  | $AFP_PASS
netatalk-1  | EOD
netatalk-1  |
netatalk-1 exited with code 139
```

The crash doesn't happen when running afppasswd stand-alone.

**Comment by rdmark** [comment]
Confirmed that https://github.com/Netatalk/netatalk/pull/937 finally unblocks this.

**Comment by rdmark** [comment]
This almost almost works now. Able to authenticate and read volumes, but the user lacks write permissions... Alpine must handle this somewhat differently.

**Comment by rdmark** [comment]
Temporarily disabling the DHX UAM in this container, since it prevents you from authenticating with OS8/OS9

**Comment by rdmark** [comment]
@dgsga This should finally be ready for testing now....

**Review by dgsga — APPROVED** [review]

**Pull request merged**
